In [6]:
#inport pandas & numpy
import pandas as pd
import numpy as np

#import csv and  convert it to pandas dateframe
df = pd.read_csv("sample.csv", encoding="utf_8")
#add calum for "group"
df["group"] = int(100)
#sort the dateframe by "skill"
sorted_df = df.sort_values(by='skill')
#devide dateframe into "male" & "female"
male = sorted_df[sorted_df.gender == "M"]
female = sorted_df[sorted_df.gender == "F"]

In [5]:
#set group number
group_number = 5
#
list(range(group_number))
male["group"]  = list(range(group_number))*( int(len(male)/group_number)) + list(range(int(len(male)%group_number)))
female["group"]  = list(range(group_number))[::-1]*( int(len(female)/group_number)) + list(range(group_number))[::-1][:len(female)%group_number]

labeled_df = pd.concat([male, female])
sorted_labeled_df = labeled_df = labeled_df.sort_values(by="group")
sorted_labeled_df

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

      name gender skill region presentation  jf  group
0     yuma      M     A     九州           RC  武道      0
9     hina      F     B     中部           RC  茶道      0
5   haruto      M     B     中部           SI  書道      0
8      yui      F     S     関西          GOV  茶道      0
6   minato      M     C     山陽          GOV  書道      1
18     aoi      F     C     東京           SI  古典      1
12    riko      F     B     九州           SI  舞踊      1
2   hiroto      M     A     関東          GOV  武道      1
17    sota      M     B     九州          EDU  古典      2
19  haruto      M     C     東北           RC  古典      2
10  himari      F     A     関東          EDU  茶道      2
3   sakura      F     C     関西          EDU  武道      2
14    yota      M     S     東京          EDU  舞踊      3
11     yua      F     A     山陽           SI  茶道      3
13     mei      F     C     東北          GOV  舞踊      3
16   asahi      M     B     東京          GOV  古典      3
15    yuto      M     B     関西           RC  舞踊      4
4     yuna      F     A     関東          EDU  書道      4
7      rin      F     C     関東           RC  書道      4
1      ren      M     S     東京           SI  武道      4